#!/usr/bin/env python

import os
import re
import logging


def main():
    logging.basicConfig(
        level=logging.DEBUG,
        format="[%(asctime)s] (%(levelname)s): '%(message)s'"
    )

    pattern = re.compile("^.*\.py$")
    for file in os.listdir("./data_ui/"):
        if pattern.match(file):
            os.remove(f'./data_ui/{file}')
            logging.warning(f"File '{file}' deleted after commit")


if __name__ == "__main__":
    main()
